=== GossJS/15092017-RedBear94/part3/3.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- Бабарицкий Павел s4107-->
<!ELEMENT info (ip | visits | ips)+>
<!ELEMENT ip EMPTY>
<!ELEMENT visits (computers | mobile_devices)+>
<!ELEMENT computers (os+)>
<!ELEMENT os (#PCDATA)>
<!ELEMENT mobile_devices (device+)>
<!ELEMENT device (#PCDATA)>
<!ELEMENT ips (ip+)>

<!ATTLIST ip
  title CDATA #IMPLIED
  addr CDATA #REQUIRED
  frequency CDATA #REQUIRED>
<!ATTLIST os name CDATA #REQUIRED>
<!ATTLIST device name CDATA #REQUIRED>
<!ATTLIST ips title CDATA #REQUIRED>

=== GossJS/15092017-RedBear94/part3/3.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Бабарицкий Павел s4107-->
<!DOCTYPE таблица PUBLIC "BabaritskiyPA" "3.dtd">
<info>
<ip title="Самый частый IP-адрес" addr="077.234.203.101" frequency="12"/>
    <visits>
        <computers>
            <os name="Windows">87</os>
            <os name="Linux">8</os>
            <os name="Mac OS">6</os>
        </computers>
        <mobile_devices>
            <device name="iPhone">5</device>
            <device name="iPad">1</device>
            <device name="Android">10</device>
        </mobile_devices>
    </visits>
    <ips title="5 наиболее встречающихся адресов в порядке убывания частоты">
        <ip addr="077.234.203.101" frequency="12"/>
        <ip addr="005.144.096.251" frequency="11"/>
        <ip addr="081.222.086.058" frequency="6"/>
        <ip addr="094.019.018.060" frequency="4"/>
        <ip addr="005.164.066.173" frequency="4"/>
    </ips>
</info>
